title: OpenAi-Playground-Jsharsh33v
email: sharsheev01@allegheny.edu
description: >- # this means to ignore newlines until "baseurl:"
  A comprehensive user manual for the OpenAI Playground,
  featuring step-by-step guides, tips, and examples.
  This site serves as a resource for understanding and mastering the functionalities of OpenAI Playground,
  presented as part of my final project for CMPSC-104.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
